[package]
name = "network_device_upgrade"
version = "0.1.0"
edition = "2021"

# Metadata
authors = ["Your Name <your.email@example.com>"]
description = "A Rust application for upgrading OS on network devices with support for multiple vendors and real-time configuration updates."
license = "MIT"
repository = "https://gitlab.com/your-repo-name"

[dependencies]
# Async runtime
tokio = { version = "1.32", features = ["full"] }

# HTTP client for API communication
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }

# Serialization and deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# File watcher for real-time updates
notify = "5.1"

# Error handling
thiserror = "1.0"

# Asynchronous traits
async-trait = "0.1.68"

# Logging
log = "0.4"
env_logger = "0.10"
